name: demo

on:
  push:
    branches:
      - state-refactor

permissions:
  contents: write

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
          enable_kvm: true
      - run: nix-shell --run 'yarn install --frozen-lockfile --immutable'
      - run: nix-shell --run 'yarn storybook:build'
      - uses: jamesives/github-pages-deploy-action@v4
        with:
          folder: dist
